server:
  port: 84

spring:
  application:
    name: naocs-consumer-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719

feign:
  sentinel:
    enabled: true #开启feign对sentinel的支持

service-url:
  provider-service: http://cloudalibaba-provider-service
