#端口号
server:
  port: 8001


spring:
  #服务名
  application:
    name: cloud-provider-payment8001
  #数据源
  datasource:
    username: root
    password: snbsnfxl
    url: jdbc:mysql://localhost:3306/spring_cloud?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    #配置数据源类型
    type: com.alibaba.druid.pool.DruidDataSource

#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sn.springcloud.entities  # 所有Entity 别名类所在包