#端口号
server:
  port: 8002

spring:
  #服务名
  application:
    name: cloud-provider-service
  #数据源
  datasource:
    username: root
    password: snbsnfxl
    url: jdbc:mysql://localhost:3306/spring_cloud?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    #配置数据源类型
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  instance:
    #当前微服务别名
    instance-id: com.sn.payment8002
    #设置访问路径显示ip地址
    prefer-ip-address: true
  client:
    #表示是否将自己注册进eurekaServer 默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息 默认为true 单节点无所谓 集群必须设置为true 才能配合ribbon使用负载均衡
    fetch-registry: true
    #注册地址
    service-url:
      # 单机版 defaultZone: http://localhost:7001/eureka
      # 集群版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sn.springcloud.entities  # 所有Entity 别名类所在包