#端口号
server:
  port: 7001

#eureka相关配置
eureka:
  instance:
    #eureka服务端的实例名称
    hostname: eureka7001.com
  client:
    # false 代表不向服务注册中心注册自己，因为它本身就是服务中心
    register-with-eureka: false
    # false 代表自己就是服务注册中心，自己的作用就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    # 设置与 Eureka Server 交互的地址，查询服务 和 注册服务都依赖这个地址
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/